name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@{{ cookiecutter.__actions_checkout_version }}
    - uses: jdx/mise-action@{{ cookiecutter.__jdx_mise_action_version }}
      with:
        version: {{ cookiecutter.__mise_tool_version }}
    - run: mise run ci
